services:
  _defaults:
    autowire: true
    autoconfigure: true

  Mosl\MagicLinkBundle\Store\MagicLinkStoreInterface:
    alias: Mosl\MagicLinkBundle\Store\DoctrineMagicLinkStore

  Mosl\MagicLinkBundle\Store\DoctrineMagicLinkStore: ~

  Mosl\MagicLinkBundle\Manager\MagicLinkManager:
    arguments:
      $defaultTtl: "%mosl_magic_link.token_ttl%"
