services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ossm\MagicLinkBundle\Store\MagicLinkStoreInterface:
    alias: Ossm\MagicLinkBundle\Store\DoctrineMagicLinkStore

  Ossm\MagicLinkBundle\Store\DoctrineMagicLinkStore: ~

  Ossm\MagicLinkBundle\Manager\MagicLinkManager:
    arguments:
      $defaultTtl: "%ossm_magic_link.token_ttl%"
